### ISSUE TITLE
need to be able to turn off gui

### ISSUE THREAD

**Issue by dlakaplan** [timstaley/drive-casa#3]
For remote connections, it is very handy to be able to turn off CASA's gui.   The normal invocation I use is:
casapy --nogui --nologger

The following accomplishes this on my local version:

--- a/drivecasa/interface.py
+++ b/drivecasa/interface.py
@@ -42,6 +42,7 @@ class Casapy(object):
                  timeout=600,
                  log2term=True,
                  echo_to_stdout=False,
+                 gui=True,
                  ):
         """
         Initialise a casapy instance.
@@ -72,7 +73,8 @@ class Casapy(object):
                 at the price of cluttering your working terminal. As an alternative,
                 it is recommended to open a separate terminal and ``tail -f`` the
                 casa_logfile.
-
+            gui: whether or not to start the CASA gui.  Setting this to False
+                turns it off (helpful for remote connections).
         """
         drivecasa.utils.ensure_dir(working_dir)
         # NB It would make sense to switch off ipython, ('noipython' flag)
@@ -85,6 +87,8 @@ class Casapy(object):
                 '--colors=NoColor',
     #             '--noipython',
                 ]
+        if not gui:
+            cmd.append('--nogui')
 

Probably this should just be a pull request rather than an issue, but this is easier for me right now.

Thanks.

**Comment by timstaley** [comment]
I'd have to check it runs as expected, but I don't think there's any reason not to add the `--nogui` flag as standard - drivecasa is intended to be run from a script, after all. I didn't include it as I assumed it had identical behaviour to the '--nologger' flag, but it sounds as if that's not the case. 

On a more general note, thanks for the feedback! Nice to know someone is getting some use out of this.

**Comment by dlakaplan** [comment]
Hi, TIm.

Thanks a lot.  I was part-way into writing this myself when I found yours, and it seems very useful so far.  CASA is a horrible pain but unavoidable for some tasks.  

I've been using a locally-modified version with the changes that I suggest.  Without the --nogui it wouldn't open over a remote ssh without X forwarding.  With that it works.  I usually use both --nologger and --nogui.

Let me know when you have a version to test.

David

**Comment by timstaley** [comment]
Hi David,
I've just tested and pushed up the change - only a one-liner. If you grab 0.6.3 from here or PyPI hopefully it will do the trick.
Cheers,
Tim
