### ISSUE TITLE
Licence and accreditation

### ISSUE THREAD

**Issue by drphilmarshall** [timstaley/drive-casa#4]
Hi Tim! 

Warren Morningstar (Stanford PHD student, @wmorning) and I are doing some ALMA simulation work, and starting to use this marvelous little interface that you have written. Thank you! For now we are simply using the pip-installed code, but in future it's possible that Warren will want to make some modifications. Thank you for providing such good documentation on how to do this. I have (in time-honored academic style) a question and a comment. First: when the time comes, which of your papers would you recommend we (read and then) cite? We'll put a note in the acknowledgments too, but a citation is worth more. Second: have you considered putting a license file in your repo? At the moment you are both encouraging people to modify your code, but also labeling it copyright - so it might be good to clear that up by adopting the MIT license or something, to make it clear that you are fully open source. I usually put a note on both accreditation and licensing in the README, and other docs too. 

Thanks again for the code! 

Phil Marshall
SLAC National Accelerator Laboratory

PS. I am visiting Oxford in May. Hopefully see you then!

**Comment by timstaley** [comment]
Hi Phil,
thanks for the note! I think it's now safe to say drive-casa has at least two developer-users who aren't me, which is gratifying.

I was initially a bit confused by your comment on licensing, but looking back at the docs (and README) I see I haven't made it explicit anywhere, so I'll have to correct that. In short: drive-casa is [BSD 3-clause licensed](https://github.com/timstaley/drive-casa/blob/master/LICENCE.txt), as that's just the default licence I've been applying to code as I make it available. As far as I can tell BSD-3 is effectively the same as the MIT license except with an additional 'no endorsement without permission' (which is almost certainly unwarranted for this stuff), but I could probably be persuaded to switch if it makes a real difference to anyone.

Regarding citation - I have a 90% complete publication on this stuff waiting for submission, which has been on the back-burner for a few weeks while I concentrate on other work, but it sounds like I should really get that done. I'll update the docs once that is published, but in the worst case if you beat me to it, just drop me an email and I should be able to justify an official stamping of [this ASCL submission](http://ascl.net/code/v/1037) by letting them know a publication is about to drop.

Ironically I shall be in the US for most of May (Hotwiring the transient universe IV + vacation) but if you're around at the beginning of May then I'll try to catch up with you!

Cheers,
Tim.

**Comment by drphilmarshall** [comment]
Nice! You should put the link to the ASCL record and a note about citing
(Staley et al in prep) for now on the README - it's good to remind people
that nothing comes for completely free, even if you don't have an arxiv
number yet. In any case, I don't think we'll be publishing before you,
which is good!

BTW if you want to "publish" your 90% paper before it is finished (so that
you can direct people to read, and thence cite it, check out gh-publisher,
demo'd here:
http://drphilmarshall.github.io/Ideas-for-Citizen-Science-in-Astronomy/
View the project on github to see how this works).

Hope to see you in May!

**Comment by timstaley** [comment]
Can't quite be bothered to set up a Travis build, but I've just uploaded the draft paper to https://github.com/timstaley/automated-radio-imaging-paper. There's a pre-built copy of the current version at https://www.dropbox.com/s/f18nga3dmv469q5/automated_radio_reduction.pdf?dl=0 if you're interested.

**Comment by drphilmarshall** [comment]
Great, thanks Tim!

**Comment by timstaley** [comment]
Reference now available in published, citable format: http://arxiv.org/abs/1505.08123
Cheers,
Tim

**Comment by drphilmarshall** [comment]
Bravo! @wmorning, please update your bibtex file :-)
