### ISSUE TITLE
Clean with multiple visibilities as input

### ISSUE THREAD

**Issue by davepallot** [timstaley/drive-casa#5]
Hi, 
The current drive-casa clean command can only handle a single visibility file as input. Casapy clean can take multiple visibilities as input (as a python list). Is it possible to add this support?

Regards
Dave

Edit: I added support to the clean command. Have a look and see if it fits. Thanks.

**Comment by timstaley** [comment]
Closed in r0.7 (https://github.com/timstaley/drive-casa/commits/r0.7.0)
